In [2]:
%matplotlib inline
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

In [3]:
%ls

 磁碟區 C 中的磁碟是 Windows
 磁碟區序號:  3444-EC57

 C:\Users\alech\GitHub\Jupyter_Workspace\Alec-Python 的目錄

2019/04/18  下午 09:17    <DIR>          .
2019/04/18  下午 09:17    <DIR>          ..
2019/04/18  下午 08:24    <DIR>          .ipynb_checkpoints
2019/04/01  下午 09:40             3,278 0103 把 Python 當計算機用.ipynb
2019/04/01  下午 09:40            66,155 0104 Jupyter 的魔術畫圖法.ipynb
2019/04/01  下午 09:40             2,835 0105 勝過計算機的變數.ipynb
2019/04/01  下午 09:40             1,623 0106 用 Markdown 做筆記.ipynb
2019/04/01  下午 09:40             4,078 0107 變數好好用.ipynb
2019/04/01  下午 09:40            13,540 0108 串列 List 是數據分析第一步.ipynb
2019/04/01  下午 09:40             4,867 0109 字串 Hello World.ipynb
2019/04/01  下午 09:40             4,729 0110 互動的開始 input.ipynb
2019/04/01  下午 09:40             4,348 0201 條件判斷.ipynb
2019/04/01  下午 09:40             3,551 0202 用迴圈做拍拍機器人.ipynb
2019/04/01  下午 09:40             2,702 0203 字串完全照我們意思格式化.ipynb
2019/04/01  下午 09:40             3,286 0204 函數的寫法初級班.ipynb
2019/04/01  下午 09:40             2,399 0205 函數練習.ipynb
2019/04/01  下午 09:40             4,973 0206 List 的切割技術.ipynb
2019/04/01  下午 09:40             1,925 0207 字串很像 list.ipynb
2019/04/01  下午 09:40             2,247 0208 List 快速生成法.ipynb
2019/04/01  下午 09:40             2,490 0209 for 迴圈.ipynb
2019/04/01  下午 09:40             2,871 0210 我們要找的資料在裡面嗎.ipynb
2019/04/01  下午 09:40             2,391 0211 if條件判斷.ipynb
2019/04/01  下午 09:40             1,958 0212 亂數好好玩.ipynb
2019/04/01  下午 09:40             5,737 0301 Python 正規套件讀入法.ipynb
2019/04/01  下午 09:40             2,655 0302 Python 正規套件讀入法之二.ipynb
2019/04/01  下午 09:40            52,890 0303 Jupyter Notebbok 數據分析標準動作.ipynb
2019/04/01  下午 09:40             2,095 0304 處理一整個 list 的數字.ipynb
2019/04/01  下午 09:40             2,404 0305 Array 真是太炫了.ipynb
2019/04/01  下午 09:40             2,456 0306 用 array 算成績.ipynb
2019/04/01  下午 09:40             2,683 0307 算全班成績（Python 的 Broadcasting）.ipynb
2019/04/01  下午 09:40            17,028 0308 Array 大變身.ipynb
2019/04/01  下午 09:40             4,775 0309 Array 快速生成法.ipynb
2019/04/01  下午 09:40            60,679 0310 Array 畫圖超方便.ipynb
2019/04/01  下午 09:40            34,847 0311 Array 快篩法.ipynb
2019/04/01  下午 09:40             2,701 0401 Python 的字典資料型態.ipynb
2019/04/01  下午 09:40             3,868 0402 超炫的互動模式-Copy1.ipynb
2019/04/01  下午 09:40             4,266 0403 超炫的互動模式之二.ipynb
2019/04/01  下午 09:40             1,848 0404 互動應用範例.ipynb
2019/04/01  下午 09:40            24,875 0405 圖形的互動.ipynb
2019/04/01  下午 09:40             9,431 0406 圖形互動看 over fitting.ipynb
2019/04/01  下午 09:40             2,077 0407 互動範例：BMI計算器.ipynb
2019/04/01  下午 09:40            63,480 0501 熊貓就像 Excel.ipynb
2019/04/01  下午 09:40            37,227 0502 用熊貓做基本數據分析.ipynb
2019/04/01  下午 09:40            15,595 0503 組裝自己的 DataFrame.ipynb
2019/04/01  下午 09:40            63,156 0504 用 Groupby 看美國哪裡最容易看到 UFO.ipynb
2019/04/01  下午 09:40            15,251 0505 Pandas 的 loc 定位法.ipynb
2019/04/01  下午 09:40            95,717 0506 玩玩真的股票資料.ipynb
2019/04/01  下午 09:40           126,977 0507 假的資料真的回歸-Copy2.ipynb
2019/04/01  下午 09:40            55,420 0601 假的資料真的回歸.ipynb
2019/04/01  下午 09:40            37,550 0602 過度擬合 Overfitting.ipynb
2019/04/01  下午 09:40            36,459 0603 訓練資料和測試資料.ipynb
2019/04/01  下午 09:40           184,557 0604 波士頓房價預測.ipynb
2019/04/01  下午 09:40           160,001 0701 用 SVM 做分類.ipynb
2019/04/03  下午 09:40            73,433 0702 判斷是哪個亞種的鳶尾花.ipynb
2019/04/01  下午 09:40            42,952 0703 KMeans 機器自動分類.ipynb
2019/04/01  下午 09:40           344,307 11 機器學習概要.ipynb
2019/04/01  下午 09:40            13,092 bear.png
2019/04/08  下午 09:28                38 file_to_read.txt
2019/04/09  下午 10:04            46,071 first_script.ipynb
2019/04/10  下午 07:56            19,488 first_script.py
2019/04/01  下午 09:40             2,507 grades.csv
2019/04/01  下午 09:40            20,544 meshgrid2.jpg
2019/04/17  下午 09:50           118,206 政大磨課師_week3.ipynb
2019/04/18  下午 09:10            44,946 政大磨課師_week4.ipynb
2019/04/18  下午 09:10               793 政大磨課師_week5_pandas.ipynb
              62 個檔案       1,991,328 位元組
               3 個目錄  367,758,671,872 位元組可用

In [4]:
df = pd.read_csv("grades.csv")

In [5]:
df.head()

    姓名  國文  英文  數學  自然  社會
0  劉俊安   9  10  15  10  13
1  胡玉華  10  10  10   8   9
2  黃淑婷  13  15   8  11  14
3  陳上紫  10  10   8   9  14
4  崔靜成  13  12  14  12  13